version: "3.0"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./build:/usr/share/nginx/html:ro 

  elastic-container:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - ek-net
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'green'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  kibana-container:
    image: docker.elastic.co/kibana/kibana:7.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-container:9200
    networks:
      - ek-net
    depends_on:
      elastic-container:
        condition: service_healthy
    ports:
      - 5601:5601

  dropbox-service:
    image: dropbox-service
    networks:
      - ek-net
    depends_on:
      elastic-container:
        condition: service_healthy
    volumes:
      - .env:/app/.env

  api-service:
    image: api-service
    networks:
      - ek-net
    depends_on:
      elastic-container:
        condition: service_healthy
    ports:
      - 3001:3001
    volumes:
      - .env:/app/.env

networks:
  ek-net:
    driver: bridge
